export const SELECTORS = {
  menuIcon: '[data-testid="MenuIcon"]',
  editIcon: '[data-testid="EditIcon"]',
  checkIcon: '[data-testid="CheckIcon"]',
  dialog: '[role="dialog"]',
  fab: '.MuiFab-root',
  card: '.MuiCard-root',
  switchInput: '.MuiSwitch-input',
  cardsViewIcon: '[data-testid="DragIndicatorIcon"]',
  tableViewIcon: '[data-testid="TableViewIcon"]',
  searchInput: 'input[placeholder="Buscar articulos"]',
  plusIcon: '[data-testid="AddIcon"]',
  minusIcon: '[data-testid="RemoveIcon"]',
  clearCartIcon: '[data-testid="RemoveShoppingCartOutlinedIcon"]',
  clearIcon: '[data-testid="ClearIcon"]',
  shippingIcon: '[data-testid="LocalShippingOutlinedIcon"]',
  filtersPanel: '[data-testid="products-filters"]',
};
